###
# Autentica como profissional
# @name login
POST http://localhost:8080/signin HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=medico@clinica.com&password=medico123

###
GET http://localhost:8080/consultas HTTP/1.1
Authorization: Bearer {{login.response.body.$.access_token}}

### Cria uma consulta (o id é gerado pelo servidor)
# @name criarConsulta
POST http://localhost:8080/consultas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

{
    "paciente": "Maria Silva",
    "medico": "Dr. João Souza",
    "data": "2026-10-01T14:30:00",
    "observacoes": "Trazer exames anteriores"
}

### Busca a consulta criada acima
GET http://localhost:8080/consultas/{{criarConsulta.response.body.$.data.id}} HTTP/1.1
Authorization: Bearer {{login.response.body.$.access_token}}

### Atualiza a consulta criada acima
PUT http://localhost:8080/consultas/{{criarConsulta.response.body.$.data.id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

{
    "paciente": "Maria Silva",
    "medico": "Dr. João Souza",
    "data": "2026-10-02T09:00:00",
    "observacoes": "Remarcada a pedido da paciente"
}

### Remove a consulta criada acima
DELETE http://localhost:8080/consultas/{{criarConsulta.response.body.$.data.id}} HTTP/1.1
Authorization: Bearer {{login.response.body.$.access_token}}

### Consulta inexistente (espera 404)
GET http://localhost:8080/consultas/00000000-0000-0000-0000-000000000000 HTTP/1.1
Authorization: Bearer {{login.response.body.$.access_token}}

### Campos obrigatórios faltando (espera 422)
POST http://localhost:8080/consultas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

{
    "paciente": "Maria Silva"
}

### Agenda do dia de hoje (página HTML da recepção)
GET http://localhost:8080/agenda HTTP/1.1
Authorization: Bearer {{login.response.body.$.access_token}}

### Consulta com HTML malicioso, para testar o escape (XSS)
POST http://localhost:8080/consultas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

{
    "paciente": "<script>alert(1)</script>",
    "medico": "Dr. João Souza",
    "data": "2026-10-01T16:00:00",
    "observacoes": "<img src=x onerror=alert(2)>"
}

### Agenda de 01/10/2026: o <script> acima deve aparecer como &lt;script&gt;
GET http://localhost:8080/agenda?data=2026-10-01 HTTP/1.1
Authorization: Bearer {{login.response.body.$.access_token}}
