name: SCA Security Gate

on: push

jobs:
  scan_sca:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v7

      - name: Scanner de vulnerabilidades
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          scanners: vuln
          severity: HIGH,CRITICAL
          exit-code: "1"
